base_url = "//docs.worldwidetelescope.org/aligner/1/"
title = "WWT Aligner Manual"
description = "The AAS WorldWide Telescope Aligner manual."
theme = "wwtguide"

[extra]
github_base = "//github.com/WorldWideTelescope/wwt-aligner"
google_analytics_id = "UA-107473046-3"
